{
    name: "Rhaegar",
    title: "Prince of Dragonstone",
    male: true,
    culture: "Valyrian",
    age: 26,
    dateOfBirth: 259,
    dateOfDeath: 283,
    actor: "",
    brothers: [""],
    sisters: ["Daenerys Targaryen"],
    mother: "",
    father: "King Aerys",
    children: ["Rhaenys", "Aegon"],
    heir: "",
    battles: [""],
    placeOfBirth: "Summerhall",
    placeOfDeath: "Trident",
    house: " House Targaryen", 
    spouses: ["Elia Martell"],
    skills: "talented musician and skilled knight",
    episodes: ["ep1", "ep2"],
    eventName: "A game of thrones, A clash with kings",
    createdAt: "01.01.2001",
    updatedAt: "01.02.2001"
}